- name: Create pathogen plugin directory
  file:
    path: ~/.config/nvim/bundle
    state: directory
    mode: 0750

- name: Create neovim autoload directory
  file:
    path: ~/.config/nvim/autoload
    state: directory
    mode: 0750

- name: Download Pathogen for VIM
  get_url:
    url: https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
    dest: ~/.config/nvim/autoload/pathogen.vim
    mode: 0660

- name: Download NERDTree
  git:
    repo: https://github.com/scrooloose/nerdtree.git
    dest: ~/.config/nvim/bundle/nerdtree

- name: Download CtrlP
  git:
    repo: https://github.com/ctrlpvim/ctrlp.vim.git
    dest: ~/.config/nvim/bundle/ctrp.vim

- name: Download YouCompleteMe
  git:
    repo: git@github.com:Valloric/YouCompleteMe
    dest: ~/.config/nvim/bundle/YouCompleteMe

- name: Compile YouCompleteMe for C/C++ support
  shell: ./install.py --clang-completer
  args:
    chdir: ~/.config/nvim/bundle/YouCompleteMe
