---
- name: Add KiCad PPA
  apt_repository:
    repo: "{{ kicad_ppa }}"
    state: present
  become: yes

- name: Update apt
  apt:
    update_cache: yes
  become: yes

- name: Install KiCad
  apt:
    name: kicad
    state: latest
  become: yes

