- name: Install packages needed for python support
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - python3-dev
    - python3-pip
  become: yes

- name: Add Neovim APT repository
  apt_repository:
    repo: 'ppa:neovim-ppa/unstable'
    state: present
  become: yes

- name: Install Neovim
  apt:
    name: neovim
    state: present
    update_cache: yes
  become: yes

- name: Install Neovim python module
  pip:
    name: neovim
    state: latest
  become: yes

- name: Update vi alternatives
  shell: update-alternatives --config vi
  become: yes

- name: Update vim alternatives
  shell: update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60 && update-alternatives --config vim
  become: yes

- name: Update editor alternatives
  shell: update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60 && update-alternatives --config editor
  become: yes

- name: Create nvim config directory
  file:
    path: "~/.config/nvim/"
    state: directory
    mode: 0755

- name: Create symlink for init.vim
  file:
    path: "~/.config/nvim/init.vim"
    state: link
    src: "~/config/nvim/init.vim"

- name: Create symlink for neovim color schemes
  file:
    path: "~/.config/nvim/colors"
    state: link
    src: "~/config/nvim/colors"


