- name: Add Neovim APT repository
  apt_repository:
    repo: 'ppa:neovim-ppa/unstable'
    state: present
  become: yes

- name: Install Neovim
  apt:
    name: neovim
    state: present
    update_cache: yes
  become: yes

- name: Create nvim config directory
  file:
    path: "~/.config/nvim/"
    state: directory
    mode: 0755

- name: Create symlink for init.vim
  file:
    path: "~/.config/nvim/init.vim"
    state: link
    src: "~/config/nvim/init.vim"

- name: Create symlink for neovim color schemes
  file:
    path: "~/.config/nvim/colors"
    state: link
    src: "~/config/nvim/colors"


