FROM ubuntu:xenial

# setup environment
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8

# setup keys
RUN apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 421C365BD9FF1F717815A3895523BAEEB01FA116

# setup sources.list
RUN echo "deb http://packages.ros.org/ros-shadow-fixed/ubuntu xenial main" > /etc/apt/sources.list.d/ros-latest.list

RUN apt-get -y update && apt-get install -y ros-kinetic-rosbash ros-kinetic-roscpp
RUN apt-get -y update && apt-get install -y python-rosdep sudo
RUN rosdep init

# Development user with passwordless sudo
RUN adduser --disabled-password --gecos '' dev
RUN adduser dev sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER dev
RUN rosdep update

RUN mkdir -p /home/dev/ws/src/
WORKDIR /home/dev/ws
COPY src/* /home/dev/ws/src/
RUN src/run.sh

