#!/bin/bash
# these directions adapted from the following sites:
#      http://clang.llvm.org/get_started.html
#      https://github.com/pacs-course/pacs/wiki/Instructions-to-install-clang-3.1-on-ubuntu-12.04.1-and-12.10

# exit on first error
set -e

sudo apt-get install g++ cmake build-essential libffi-dev

# get llvm
svn co http://llvm.org/svn/llvm-project/llvm/trunk llvm

# get clang
cd llvm/tools
svn co http://llvm.org/svn/llvm-project/cfe/trunk clang
cd ../..

# Checkout extra Clang Tools: (optional)
cd llvm/tools/clang/tools
svn co http://llvm.org/svn/llvm-project/clang-tools-extra/trunk extra
cd ../../../..

# Checkout Compiler-RT
cd llvm/projects
svn co http://llvm.org/svn/llvm-project/compiler-rt/trunk compiler-rt
cd ../..

# Build LLVM and Clang using cmake
mkdir build
cd build
cmake ../llvm/
make -j5
