---
- name: Import the ROS repository key
  apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      state: present
      id: C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
  become: yes

- name: Add ROS apt repo
  apt_repository:
    repo: "deb http://packages.ros.org/{{ ros_apt_repo }}/ubuntu {{ ansible_distribution_release }} main"
    state: present
  become: yes

- name: Update apt
  apt:
    update_cache: yes
  become: yes

- name: Install ROS
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - python3-rosdep
    - python3-rosinstall
      # Not yet working on 20.04: https://github.com/catkin/catkin_tools/issues/597
      # - python3-catkin-tools
    - python3-bloom
    - "{{ ros_deb }}"
  become: yes

- name: Initialize rosdep
  shell: rosdep init
  args:
    creates: "{{ rosdep_default_sources_file }}"
  become: yes

- name: Update rosdep
  become: yes
  shell: rosdep update
