---
- name: Import the ROS repository key
  apt_key:
      keyserver: hkp://ha.pool.sks-keyservers.net:80
      state: present
      id: 421C365BD9FF1F717815A3895523BAEEB01FA116
  become: yes

- name: Add ROS apt repo
  apt_repository:
    repo: "deb http://packages.ros.org/{{ ros_apt_repo }}/ubuntu {{ ansible_distribution_release }} main"
    state: present
  become: yes

- name: Update apt
  apt:
    update_cache: yes
  become: yes

- name: Install ROS
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - python-rosdep
    - python-rosinstall
    - python-catkin-tools
    - python-bloom
    - "{{ ros_deb }}"
  become: yes

- name: Initialize rosdep
  shell: rosdep init
  args:
    creates: "{{ rosdep_default_sources_file }}"
  become: yes

- name: Update rosdep
  become: yes
  shell: rosdep update
