export BASH_LOCAL_DIR=$HOME/config/bash
export DROPBOX_DIR=$HOME/Dropbox

alias rebash="source $HOME/.bashrc"
alias emacs='emacs -nw'

export EDITOR=emacs

PS1="\n\[\033[32m\][\w]\[\033[0m\]\n\[\033[1;36m\]\u@\[\033[32m\]\h\[\033[1;33m\]-> \[\033[0m\]"

ROS_BASHRC=$HOME/vcs/ros-shell-utils/bashrc/bashrc.sh
if [ -f $ROS_BASHRC ]; then
  source $ROS_BASHRC
fi;

export PATH=$HOME/config/scripts:$PATH

# use vim keybindings in bash
# set -o vi

# if this variable isn't set properly, tmux won't use 256 colors
[ -z "$TMUX" ] && export TERM=xterm-256color

# if available, use the version of vim from vim-nox package, since it is compiled
# with ruby support, which is needed for command-t
VIM_NOX=/usr/bin/vim.nox
if [ -f ${VIM_NOX} ]; then
    alias vim=${VIM_NOX}
fi;

source $BASH_LOCAL_DIR/funcs.sh

git config --global user.email "jbinney@willowgarage.com"
git config --global user.name "Jon Binney"
